kbayashi/TestFirebase

.idea/gradle.xml, .idea/jarRepositories.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/testfirebase/ChatActivity.kt, app/src/main/res/layout/activity_chat.xml
=> FirstCommit

app/src/main/res/layout/activity_chat.xml
=> 左上にテキストをテスト配置しました

.idea/render.experimental.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/testfirebase/UserLoginActivity.kt, app/src/main/res/layout/activity_user_login.xml
=> user_login_branch

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/testfirebase/MainActivity.kt, app/src/main/java/com/example/testfirebase/User.kt, app/src/main/java/com/example/testfirebase/UserListFragment.kt, app/src/main/java/com/example/testfirebase/UserRegistarActivity.kt, app/src/main/java/com/example/testfirebase/userListAdapter.kt, app/src/main/res/drawable/ic_baseline_person_add_24.xml, app/src/main/res/drawable/ic_baseline_search_24.xml, app/src/main/res/layout/user_list_fragment.xml, app/src/main/res/layout/user_list_row.xml, app/src/main/res/menu/user_list_fragment_menu.xml
ユーザリストと最新のトークリストのデザインと処理を作りました。
マージしてください
=> user_list_inDate_branch

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/testfirebase/MainActivity.kt, app/src/main/java/com/example/testfirebase/UserRegistarActivity.kt, app/src/main/java/com/example/testfirebase/selectDialogAdapter.kt, app/src/main/java/com/example/testfirebase/selectDialogRadio.kt, app/src/main/java/com/example/testfirebase/userListAdapter.kt, app/src/main/res/drawable/dialog_cansel_button.xml, app/src/main/res/drawable/dialog_main_color.xml, app/src/main/res/drawable/dialog_recyclerview_border.xml, app/src/main/res/drawable/dialog_select_button.xml, app/src/main/res/drawable/dialog_title.xml, app/src/main/res/font/acme.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_title.xml, app/src/main/res/layout/activity_user_login.xml, app/src/main/res/layout/activity_user_registar.xml, app/src/main/res/layout/select_dialog_item_row.xml, app/src/main/res/layout/select_dialog_radio.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
登録画面のレイアウトを調整。ラジオボタンで選択できるダイアログを作成
=> layout_change_branch

app/src/main/java/com/example/testfirebase/User.kt, app/src/main/java/com/example/testfirebase/UserRegistarActivity.kt
=> user_class_fix

app/src/main/java/com/example/testfirebase/UserPlofileEditActivity.kt, app/src/main/res/drawable/ic_baseline_camera_alt_24.xml, app/src/main/res/layout/activity_user_my_profile.xml, app/src/main/res/layout/activity_user_plofile_edit.xml
This reverts commit d454eece
ユーザープロフィール編集画面を作成しました
=> ユーザープロフィール編集画面を作りました

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/testfirebase/LatestChatListFragment.kt, app/src/main/java/com/example/testfirebase/MainActivity.kt, app/src/main/java/com/example/testfirebase/Message.kt, app/src/main/java/com/example/testfirebase/TitleActivity.kt, app/src/main/java/com/example/testfirebase/UserListFragment.kt, app/src/main/java/com/example/testfirebase/latestChatListAdapter.kt, app/src/main/res/layout/latest_chat_row.xml, app/src/main/res/layout/user_list_row.xml
=> latest_message_branch

app/src/main/java/com/example/testfirebase/UserProfileEditActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditPlainTextActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditRadioButtonActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditSpinnerActivity.kt, app/src/main/java/com/example/testfirebase/selectDialogMultiple.kt, app/src/main/res/values/age.xml, app/src/main/res/values/life_expectancy.xml, app/src/main/res/values/prefecture.xml, app/src/main/res/values/sick.xml
DBに更新（だけ）する処理を追加できました。見た目が変わらないのは時間がありませんでした。代わりに武田がコサックダンスします。Firebase上ではしっかり変わってますのでご査収ください。
=> User profile

app/src/main/AndroidManifest.xml
=> アプリインストール時になぜかアイコンが2つになるバグを特定、修正した

app/src/main/res/layout/activity_title.xml
=> タイトル最初のアプリ説明文が端末によっては見切れる可能性があったが、ある程度はマシになった

app/src/main/res/layout/chat_me_row.xml, app/src/main/res/layout/chat_you_row.xml
=> 英文字を打つとすべて大文字になってしまうバグを修正

app/src/main/java/com/example/testfirebase/UserProfileEditActivity.kt, app/src/main/res/layout/activity_user_profile_edit.xml
=> ユーザープロフィール編集画面のUI変更

app/src/main/res/layout/activity_title.xml
=> 端末のサイズが変わっても文字がすべて入るように調整。スクロールを導入

app/src/main/java/com/example/testfirebase/UserMyProfileActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileActivity.kt, app/src/main/res/layout/activity_user_my_profile.xml, app/src/main/res/layout/activity_user_profile.xml
=> ユーザープロフィール画面のUI変更

app/src/main/java/com/example/testfirebase/messageAdapter.kt
=> チャット画面で、相手のアイコンが自分のアイコンになってしまうバグを修正した

app/src/main/java/com/example/testfirebase/User.kt, app/src/main/java/com/example/testfirebase/UserProfileEditActivity.kt
=> プロフィール画像変更処理の追加

.idea/compiler.xml, .idea/gradle.xml, .idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/testfirebase/UserListFragment.kt, app/src/main/java/com/example/testfirebase/UserMyProfileActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditPlainTextActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditRadioButtonActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditSpinnerActivity.kt, app/src/main/res/layout/activity_user_my_profile.xml, app/src/main/res/layout/activity_user_profile_edit.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Profile intent 2

app/src/main/java/com/example/testfirebase/ChatActivity.kt, app/src/main/java/com/example/testfirebase/UserListFragment.kt, app/src/main/java/com/example/testfirebase/UserProfileActivity.kt, app/src/main/java/com/example/testfirebase/friendAddDialog.kt, app/src/main/java/com/example/testfirebase/friendTemporaryRegistrationAdapter.kt, app/src/main/java/com/example/testfirebase/timeLineFragment.kt, app/src/main/java/com/example/testfirebase/userListAdapter.kt, app/src/main/res/layout/activity_user_profile.xml, app/src/main/res/layout/time_line_recyclerview_row.xml, app/src/main/res/layout/user_list_fragment.xml
=> friend_add_branch

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/testfirebase/UserMyProfileActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditActivity.kt
manifestの不具合を修正しました。急ぎMasterにマージします
=> Check dialog

app/src/main/java/com/example/testfirebase/UserProfileEditActivity.kt, app/src/main/java/com/example/testfirebase/UserProfileEditCheckDialog.kt, app/src/main/java/com/example/testfirebase/selectDialogMultipleAdapter.kt
=> 趣味ダイアログと病名ダイアログを完成させました。

app/src/main/java/com/example/testfirebase/UserListFragment.kt
コンフリクト時にうっかり「}」を消してしまったのを見つけたので即刻修正します
=> コンフリクトのバグを修正

app/src/main/java/com/example/testfirebase/TimeLineAddActivity.kt, app/src/main/java/com/example/testfirebase/TimeLineCommentActivity.kt, app/src/main/java/com/example/testfirebase/UserRegistarActivity.kt, app/src/main/java/com/example/testfirebase/timeLineListAdapter.kt, app/src/main/res/drawable/ic_baseline_chat_bubble_outline_24.xml, app/src/main/res/drawable/ic_baseline_thumb_up_24.xml, app/src/main/res/drawable/ic_baseline_yellow_thumb_up_24.xml, app/src/main/res/layout/time_line_recyclerview_row.xml
=> goodボタンを押したら色がつくように修正
